project:
  type: website
  output-dir: ../docs
  render:                
    - index.qmd
    - dictionary_documentation.qmd
    - figures.qmd
  resources:
    - ../figures/**

website:
  title: "PHES Dictionary"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dictionary_documentation.qmd
        text: Dictionary
      - href: figures.qmd
        text: Figures
  search: true
  page-navigation: true

execute:
  dir: project
  warning: false
  message: false
  freeze: auto

format:
  html:
    theme: default
    toc: true
    toc-depth: 2
    anchor-sections: true
    css: assets/styles.css
    code-copy: true
    link-external-newwindow: true
    smooth-scroll: true
