name: Update Website

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for update (optional)'
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libxml2-dev \
            libssl-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libnode-dev \
            libx11-dev \
            pandoc

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore renv packages
        uses: r-lib/actions/setup-renv@v2

      - name: Extract CSVs from Excel (if Excel file exists)
        run: |
          if [ -f "data_raw/2025-07-15_ScopingReview_ReportedConcepts.xlsx" ]; then
            echo "Excel file found - extracting CSVs..."
            Rscript R/extract_excel_to_csv.R
          else
            echo "No Excel file found - using existing CSVs"
          fi

      - name: Validate CSV data
        run: Rscript R/validate_csv_data.R

      - name: Render Quarto website
        run: quarto render

      - name: Commit updated website
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update website via GitHub Actions${REASON:+ - $REASON}"
            git push
          fi
        env:
          REASON: ${{ github.event.inputs.reason }}

      - name: Summary
        run: |
          echo "✅ Website updated successfully!"
          echo "View at: https://big-life-lab.github.io/phes-ef-scope-private/"
